# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77336fdbd7fa5f25af501ac3afe127abbec762f39d80887ffbfc3d1db8f4a6be3b179ee11ccba4f8470e5aff21a2a870b63202246f0e706797e0b2989060997f

test:
  secret_key_base: c9261008e69d5fceaec59268b023f4783bb79a5e8066372e8c99cb0a5861e280fbbf7466b45a702c52ad9b5138d4bd8320493c0c825bc3224762e01ce6455ebc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
